### ISSUE TITLE
For-loops cause incorrect error

### ISSUE THREAD

**Issue by sagacity** [dparnell/intellij-wgsl#1]
If I create a simple for-loop like the one from the WGSL spec, like so:

```
for(var i: i32 = 0; i < 4; i++) {
  if (a == 0) {
    continue;
  }
  a = a + 2;
}
```

Then intellij-wgsl will emit an error at the first plus of `i++`:
```
<postfix expression>, WGSLTokenType.EQUAL or WGSLTokenType.PAREN_LEFT expected, got '+'
```

I notice that [wgpu](https://github.com/gfx-rs/wgpu) doesn't seem to accept this syntax either, even though it's in the spec, so I am assuming this is a fairly recent change. Changing `i++` to `i = i + 1` works fine.

**Comment by dparnell** [comment]
The spec has indeed changed since I built the parser for the plugin. I'm looking into what needs to be done to support the syntax

**Comment by sagacity** [comment]
Great! Or perhaps it's a good idea to just wait until the spec settles down a bit more. Regardless, thanks for the plugin :)

**Comment by dparnell** [comment]
I've added support for the syntax, now I need to figure out the release stuff so it automatically uploads the new version to the jetbrains store. The provided github actions build stuff is currently failing

**Comment by dparnell** [comment]
I have created a new release and submitted it to the jetbrains store. You can either try installing the release manually from here or wait for them to approve it and download the update.

**Comment by sagacity** [comment]
Oh wow, that's awesome. Thanks for the quick response. I'll grab the release manually and see how I get on.

**Comment by dparnell** [comment]
let me know how it goes so I can close this issue

**Comment by sagacity** [comment]
It works perfectly, thank you for your time.
