### ISSUE TITLE
Struct member separators: comma vs semicolon

### ISSUE THREAD

**Issue by monfera** [dparnell/intellij-wgsl#18]
I get a Chrome Canary warning about how the semicolon is deprecated as a `struct` member separator: 
`warning: use of deprecated language feature: struct members should be separated with commas`

The current WGSL spec also [specifies](https://www.w3.org/TR/WGSL/#struct-types) commas for struct member separation.

However this awesome WGSL plugin will cause a red error mark in the gutter: `SEMICOLON expected, got ','`

In the bnf:
```
struct_member ::=
--
74 | attribute_list* field SEMICOLON
```

**Comment by dparnell** [comment]
This should be fixed in the next release. I have just pushed it to github and once it has built I will submit it to Jetbrains for validation. It usually takes a couple of days for them to review any updates.
