### ISSUE TITLE
@stage(...) is now @vertex / @fragment / @compute

### ISSUE THREAD

**Issue by tobia** [dparnell/intellij-wgsl#22]
See https://gpuweb.github.io/gpuweb/wgsl/#entry-point-decl

Need to update ATTRIBUTE_NAMES and also custom tests like `.equals("stage(fragment)"` and such.

**Comment by dparnell** [comment]
I'll take a look and see what I can see

**Comment by dparnell** [comment]
I have pushed a fix for this to github and once it finishes building I will submit it to the IntelliJ store. After that it should become available in a couple of days after they approve it.

**Comment by dparnell** [comment]
This should be available on the IntelliJ store now
