### ISSUE TITLE
Support preprocessor #ifdef, #define, ...

### ISSUE THREAD

**Issue by ralfbiedert** [dparnell/intellij-wgsl#24]
Thanks a lot for this plugin! I was wondering if you could support syntax highlighting preprocessor directives, as some WGSL variants use them, for example WGSL in Bevy:

![image](https://user-images.githubusercontent.com/301288/173344150-eafd6ed6-6721-4913-9b43-eca986c09139.png)

**Comment by dparnell** [comment]
I'm glad you are enjoying the plugin and finding it useful.

Is there a spec for these pre-processor directives or do you want something hat just treats it more or less like a variation of single line comments?

**Comment by ralfbiedert** [comment]
To be honest I don't know what the spec says about these, the best I could find after a quick search [was this](https://github.com/gpuweb/gpuweb/issues/568), so my wild guess is the exact syntax and symbols are Bevy specific, with a generally agreed upon `#SOMETHING`  for lines to be preprocessed. 

For me personally, all I'm after is having some syntax highlighting working.

- The most basic case could be highlighting the entire line in one color ("Metadata", maybe "Template language" style?)
- A little bit more advanced could be to separate out the first token (`#ifdef`) from the rest of each line (`SKINNED`)

Either way would work for me.

**Comment by dparnell** [comment]
I've just submitted a new build to Jetbrains for approval. I have gone with the basic highlighting for now until a more formal spec of the preprocessor can be made.
I looked at the bevy source and found the preprocessor included there is fairly simple and a more detailed description of the available directives could be made using that code.

**Comment by ralfbiedert** [comment]
Just got the latest plugin, works really well, thanks!
