### ISSUE TITLE
Icon placeholder(?) in "Quick Documentation" 

### ISSUE THREAD

**Issue by ralfbiedert** [dparnell/intellij-wgsl#28]
Being able to invoke "Quick Documentation" (F1 in my key binding) on attributes is great, and I like that I can read the specification text.  The only nit is there is a small weird icon placeholder showing up too:

![image](https://user-images.githubusercontent.com/301288/173867892-5f8c38c7-707b-4ab3-b2b7-8017f711d4b4.png)

**Comment by dparnell** [comment]
This should be fixed in the next release

**Comment by dparnell** [comment]
Jetbrains has approved the release with this fix. Let me know if this fixes the issue.

**Comment by ralfbiedert** [comment]
Fixed, thanks!
