### ISSUE TITLE
for loop update should allow compound assignment

### ISSUE THREAD

**Issue by crowlKats** [dparnell/intellij-wgsl#34]
Example: https://github.com/gfx-rs/wgpu/blob/master/wgpu/examples/shadow/shader.wgsl#L86

**Comment by dparnell** [comment]
This should be fixed in the next release. It will take Jetbrains a couple of days to approve it.

**Comment by dparnell** [comment]
The 0.0.16 release should now be available on the Jetbrains store. Let me know if this fixes the issue.

**Comment by crowlKats** [comment]
yep, it does work now, thanks!

**Comment by dparnell** [comment]
Excellent :)
