### ISSUE TITLE
Not compatible with the version of your running IDE (WebStorm 2022.2)

### ISSUE THREAD

**Issue by 0x1f57** [dparnell/intellij-wgsl#36]
Cannot be used in the latest version(2022.2)  of IDE

**Comment by dparnell** [comment]
I'll take a look and see what I can see

**Comment by ralfbiedert** [comment]
Not sure if this is the same error, but I have similar problems in CLion:

![image](https://user-images.githubusercontent.com/301288/181435325-a28b0aff-817e-4991-a662-10dfe80ee775.png)

**Comment by dparnell** [comment]
this is the same issue. I'm going to try submitting a new build with just the max version number changed. Who knows it might just work 😉

**Comment by LoganDark** [comment]
![image](https://user-images.githubusercontent.com/4723091/181445089-85c01b04-82f7-43f6-a998-b39e35af18d4.png)

**Comment by dparnell** [comment]
I'm working on getting an update for this out. It will take Jetbrains a couple of days to process. Github actions are currently being painful. Once I get that sorted out it should become available soon after.

**Comment by dparnell** [comment]
ok, I have sorted out the github actions problem and the new release is available for manual download from github. It should become available on the Jetbrains plugin store in a couple of days.

**Comment by dparnell** [comment]
Wow! The Jetbrains reviewers came through and the update is now available for download from the plugin store. Can you please install the update and confirm it works with your local install.
Thanks :)

**Comment by ralfbiedert** [comment]
Yup, works :)

![image](https://user-images.githubusercontent.com/301288/181705181-4621e857-0876-4021-b3e3-9139e486f2d6.png)

Thanks!

**Comment by dparnell** [comment]
Excellent 😄
