### ISSUE TITLE
[BUG] ">>" - Syntax error that isn't an error 

### ISSUE THREAD

**Issue by lucypero** [dparnell/intellij-wgsl#37]
```
struct ModelUniform {
    model: array<mat4x4<f32>>,
};
```

It outputs `WGSLTokenType.GREATER_THAN expected, got '>>'` at the `>>`

Inserting a space in-between the 2 `>` characters, the error disappears.

**Comment by dparnell** [comment]
I'll take a look and see what I can come up with.

**Comment by dparnell** [comment]
This is turning out to be a nasty one to fix. The lexer is treating the `>>` as a single token, but when I I take out the token and replace it with two `>` tokens in the grammar this makes other syntax behave a bit oddly. I am still looking into it.

**Comment by dparnell** [comment]
This should be fixed in the next release. I will hopefully be finalizing the fix some time today, and then it will probably take a couple of days for Jetbrains to approve the update

**Comment by dparnell** [comment]
I have submitted a new release to the Jetbrains store. It should become available soon. Let me know if this solves your issue.

**Comment by dparnell** [comment]
This should be available in the Jetbrains marketplace now. Let me know if this works for you

**Comment by lucypero** [comment]
> This should be available in the Jetbrains marketplace now. Let me know if this works for you

It works. Thank you so much.

**Comment by dparnell** [comment]
Excellent. It was a tricky one.
