### ISSUE TITLE
I'd like the option to set the WSGL Version.

### ISSUE THREAD

**Issue by maccesch** [dparnell/intellij-wgsl#38]
No every library is always on the latest version and you have to use older syntax. It would be awesome if it didn't show up as deprecated because I could set the version I'm writing for.

Thanks for this awesome plugin!

**Comment by dparnell** [comment]
That's a really interesting idea. I think it should be possible to have a special comment at the top of the file that tells the plugin which version of the wgsl spec the file contains. How does that sound?

**Comment by maccesch** [comment]
Yeah that would be a possibility. Another one would be to have a per project setting. Not sure which is better.
I guess whatever is easier for you to implement 😄

**Comment by dparnell** [comment]
This should be available in the next release. It will probably take the Jetbrains team a couple of days to approve the new version of the plugin.

The following is taken from the change log:

- allow older syntax deprecation warnings to be turned off - #38
    - adding a comment as the first line in the file like the following will allow deprecation warnings to be disabled
      ```
      \\+ old-attribute-syntax old-struct-syntax old-attributes
      ```
      - old-attribute-syntax disables the warning on the old bracket style attributes
      - old-struct-syntax disable the warning for semicolons separating `stuct` members
      - old-attributes disables the warning for old deprecated attributes such as `stage`

Let me know if this does what you need

**Comment by dparnell** [comment]
This should be available in the Jetbrains marketplace now. Let me know if this works for you

**Comment by maccesch** [comment]
Thank you very much!
