### ISSUE TITLE
Fix matrix trailing space issues

### ISSUE THREAD

**Issue by terrarier2111** [dparnell/intellij-wgsl#41]
Writing something like:
`
let model_matrix = mat4x4<f32>(
            instance.model_matrix_0,
            instance.model_matrix_1,
            instance.model_matrix_2,
            instance.model_matrix_3,
        );
`
causes red thingies to pop up and formatting to get messed up, removing the trailing semicolon fixes these issues

**Comment by dparnell** [comment]
the issue appears to be the trailing comma. Without that it accepts the line.  I will update the parser to accept this syntax

**Comment by dparnell** [comment]
I have submitted a new version to the Jetbrains marketplace. It usually takes them a couple of days to approve new versions.
Let me know if this fixes the issue.

**Comment by dparnell** [comment]
this should be available in the Jetbrains marketplace now

**Comment by terrarier2111** [comment]
It works like a dream, tysm
