### ISSUE TITLE
Wrong types get suggested

### ISSUE THREAD

**Issue by terrarier2111** [dparnell/intellij-wgsl#43]
The plugin suggests me types called "float32" and "float16" if i type "f" although it should suggest "f32" and "f16" instead!

**Comment by dparnell** [comment]
I have just pushed a fix for this. It should be available in the Jetbrains marketplace in a couple of days once they approve the update

**Comment by dparnell** [comment]
This should be available on the Jetbrains market place now. Let me know if this fixes your problem.,

**Comment by terrarier2111** [comment]
This works now, thx!
