### ISSUE TITLE
Add support for `const` keyword

### ISSUE THREAD

**Issue by terrarier2111** [dparnell/intellij-wgsl#44]
Currently writing const looks like an other invalid expression, fix this by adding support for the `const` keyword and thus const expressions

**Comment by dparnell** [comment]
I have just pushed a fix for this. It should be available in the Jetbrains marketplace in a couple of days once they approve the update

**Comment by dparnell** [comment]
This should be available on the Jetbrains market place now. Let me know if this fixes your problem.,

**Comment by terrarier2111** [comment]
Thanks! This works unfortunately only partially, the `const` keyword doesn't get flagged anymore, but the ``/`` in:
``const INV_ATLAS_SIZE: f32 = 1.0 / 2048.0;`` does get marked red

**Comment by dparnell** [comment]
This is going to take a bit of fixing properly. The issue is the grammar is expecting the value to be a simple constant. I will change it to allow any expression.

**Comment by dparnell** [comment]
This should be fixed in the 0.0.22 release on the Jetbrains marketplace now.
