### ISSUE TITLE
Add support for constant sized arrays

### ISSUE THREAD

**Issue by terrarier2111** [dparnell/intellij-wgsl#45]
Fields like: array<vec4<f32>, 10>

should be valid, but the constant size param is marked as red

**Comment by dparnell** [comment]
I have just pushed a fix for this. It should be available in the Jetbrains marketplace in a couple of days once they approve the update

**Comment by dparnell** [comment]
This should be available on the Jetbrains market place now. Let me know if this fixes your problem.,

**Comment by terrarier2111** [comment]
This works now, thanks for your great work!
