### ISSUE TITLE
Custom imports support

### ISSUE THREAD

**Issue by paul-hansen** [dparnell/intellij-wgsl#53]
Any chance we could get custom import support like wgsl-analyzer has? 
https://github.com/wgsl-analyzer/wgsl-analyzer/tree/main/editors/code#custom-imports

See here for how it's used with Bevy: https://github.com/bevyengine/bevy/issues/5561

Regardless, the work you have done with this plugin has been very appreciated!

**Comment by dparnell** [comment]
I imagine I could make the plugin ignore any line that starts with `#` at the very least.

**Comment by dparnell** [comment]
The plugin already ignores any line starting with `#`, so what is it you want the plugin to do?

**Comment by paul-hansen** [comment]
Sorry I should have tried to clarify. Thanks for asking.

Bevy has a simple preprocessor that basically inserts the file it imports at the location of the import at compile time. If this plugin could support auto completion of the imported variables, function names etc. that would be super helpful. wgsl-analyzer for vscode does this by having the user provide a map of import names and the file name to use for the import.

I totally get that if you aren't using bevy you aren't going to be very motivated to add this so feel free to close this if it isn't something you are interested in supporting. It isn't part of the WGSL spec so that's an understandable stance.
Lmk if you don't want to but would be willing to consider a PR to add support and I might attempt it, I'm not familiar with jetbrains plugin dev yet and just started a new job so it would probably be a ways down the road.

**Comment by dparnell** [comment]
AH, I see what you're after. It might be easier to integrate with `wgsl-analyzer` in some way to get the full benefits of code completion and so on.

I'm more than happy to accept a PR with any changes you make.
