### ISSUE TITLE
Plugin not working anymore in newer IDE builds 232 or higher

### ISSUE THREAD

**Issue by FoxelFox** [dparnell/intellij-wgsl#63]
Updated my Webstorm to Version 2023.2 and got this error

```
Plugin 'WGSL Support' (version '0.0.26') is not compatible with the current version of the IDE,
because it requires build 231.* or older but the current build is WS-232.8660.143
```

And I would like to take this opportunity to thank you for this helpful plugin =)

**Comment by dparnell** [comment]
I have just published 0.0.27 which should fix this. It usually takes a couple of days for the Jetbrains store to approve the release.

**Comment by dparnell** [comment]
The 0.0.27 release has been approved for distribution on the Jetbrains store. You should be able to use the plugin with the 2023.2 releases of CLion and IntelliJ now

**Comment by FoxelFox** [comment]
Thanks working now
