### ISSUE TITLE
Highlighting breaks on "binding_array" declaration

### ISSUE THREAD

**Issue by jaakkojakara** [dparnell/intellij-wgsl#67]
I'm facing some problems with `binding_array` declarations.

With this code:
```
@group(0) @binding(0)
var example_binding: binding_array<texture_2d<f32>>;
```
I get the following error: `WGSLTokenType.EQUAL or WGSLTokenType.SEMICOLON expected, got '<'` on the first open angled bracket, and highlighting for the rest of the file is broken.

**Comment by dparnell** [comment]
It looks like the plugin does not currently understand `binding_array` I will take a look at the parser definition and see what else has changed recently.

**Comment by dparnell** [comment]
According to the wgsl spec `binding_array` is a reserved word and must not appear in wsgl source code.

**Comment by jaakkojakara** [comment]
Thanks for checking this, so `binding_array` is actually a feature in wgpu flavour of wgsl, where it is used as a frontend for naga and subsequently transpiled to some other shader format depending on the platform.

The reason it is a reserved keyword in webgpu spec is actually because wgpu project asked for  that, so that it is clear it's not supported in web flavour of wgsl. See this PR: [https://github.com/gpuweb/gpuweb/issues/2794](https://github.com/gpuweb/gpuweb/issues/2794)

One question I guess is does this plugin aim to support wgsl files written for wgpu? For context, I did a quick and dirty search on GitHub on projects that contain .wgsl files, and seems that _most_ of them are written for wgpu, so at least currently it seems to be a major use case for wgsl language.

edit: FWIW, seems that wgsl-plugin for vscode does support it: [https://github.com/wgsl-analyzer/wgsl-analyzer/issues/24](https://github.com/wgsl-analyzer/wgsl-analyzer/issues/24)

**Comment by dparnell** [comment]
I use the plugin for wgpu stuff also. I can add it in without too much hassle.

**Comment by dparnell** [comment]
I have just submitted a new release to the Jetbrains store with support for `binding_array`. It can take a couple of days for them to process the new release.

**Comment by dparnell** [comment]
The updated plugin should be available in the Jetbrains store now. let me know if this fixes your issue.

**Comment by jaakkojakara** [comment]
Updated the plugin and everything works now, thank you so much!
