### ISSUE TITLE
EAP Support

### ISSUE THREAD

**Issue by lilithium-hydride** [dparnell/intellij-wgsl#7]
When using the latest CLion EAP (CL-221.4906.7), the plugin is not listed in the Marketplace, and when I attempt to install it from disk, I get:
> Plugin 'WGSL Support' (version '0.0.5') is not compatible with the current version of the IDE, because it requires build 213.* or older but the current build is CL-221.4906.7

I don't know what all (if anything) has changed between the versions, but if it's something as simple as editing the plugin manifest, it'd be nice to have support for EAP builds.

**Comment by dparnell** [comment]
I'll take a look at the manifest and see if I can remove the restriction. It will take a couple of days for Jetbrains to approve any update

**Comment by dparnell** [comment]
This should be fixed in 0.6.0 once it becomes available

**Comment by lilithium-hydride** [comment]
Awesome, thank you!

**Comment by dparnell** [comment]
The build/release stuff is being a pain. It seems to be different every time 😢

**Comment by dparnell** [comment]
ok, a new release has been submitted and the manual install is available from the 0.6.0 release on github. Let me know if it works for you.

**Comment by lilithium-hydride** [comment]
Works perfectly for me

**Comment by dparnell** [comment]
Excellent
