### ISSUE TITLE
Support multi line import statements

### ISSUE THREAD

**Issue by ewized** [dparnell/intellij-wgsl#71]
When using bevy and their wgsl support, the imports could be multi line. Bellow is an example of that shows multi line import failing but a single line import works fine.

### singleline
![image](https://github.com/dparnell/intellij-wgsl/assets/1458852/a1a8118b-2f98-4045-88d6-5f8408bc343c)
### multiline
![image](https://github.com/dparnell/intellij-wgsl/assets/1458852/a2eeb8db-6f17-4609-b676-66eb79805c68)

**Comment by dparnell** [comment]
I'll take a look and see what I can do.

**Comment by dparnell** [comment]
I have submitted version 0.0.30 to the Jetbrains store. It can take them a couple of days to approve the update. Let me know if this fixes the problem for you :)

**Comment by ewized** [comment]
@dparnell Thanks for the quick turnaround that resolved this issue
