### ISSUE TITLE
Support @-based syntax for attributes

### ISSUE THREAD

**Issue by misdake** [dparnell/intellij-wgsl#9]
WGSL Syntax Proposal:
https://github.com/gpuweb/gpuweb/issues/2243

Proposal discussed here:
https://github.com/gpuweb/gpuweb/wiki/WGSL-2022-01-18-(APAC)-Minutes#are-double-brackets-necessary-for-attributes--issue-2243

Relevant WGSL spec PR:
https://github.com/gpuweb/gpuweb/pull/2517
https://github.com/gpuweb/cts/pull/938

**Comment by dparnell** [comment]
I've started building support for this

**Comment by dparnell** [comment]
I have submitted version 0.0.7 for approval. It should contain initial support for the new attribute syntax

**Comment by misdake** [comment]
Looks good, thank you for your time and effort.

**Comment by dparnell** [comment]
My pleasure :)
